name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fc4ecde641411282d997430c9eb7e8984fbe42f112bdfd8de553e29d7a754002"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
