name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35384ea3e8403c27ca6eda62bab75554564d62e126e38376b6061595fbeaf6e3"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
