name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1cacda2917c30947a88ba23552b617234be6c872016214e00704f0c8b3f786ba"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
