name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af9cf7d555e4a6fb0786a8067beb275cc1562656e1a532ab8e55492a7972be43"

[versions]
forge = "47.4.20"
minecraft = "1.20.1"
