name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80533be2f1424e1fc6f5477581a5fab817bc493e97dbc8b3d8f07dee02929ee0"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
