name = "Frigid Abyss"
author = "Raeffi"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "36efd3a2cf30ff09c5e62ebae4024b113dac886a33b315b04894765580c3d4ec"

[versions]
forge = "47.2.23"
minecraft = "1.20.1"
