// priority: 0

// Visit the wiki for more info - https://kubejs.com/

ClientEvents.lang('en_us', e => {
    const rename = (item, newName) => e.add(Item.of(item).item.getDescriptionId(), newName)
    
    rename("pneumaticcraft:ingot_iron_compressed", "Pressure Treated Steel Ingot")
    rename("pneumaticcraft:compressed_iron_block", "Block of Pressure Treated Steel")

    rename("pneumaticcraft:compressed_iron_helmet"      , "Pressure Treated Steel Helmet")
    rename("pneumaticcraft:compressed_iron_chestplate"  , "Pressure Treated Steel Chestplate")
    rename("pneumaticcraft:compressed_iron_leggings"    , "Pressure Treated Steel Leggings")
    rename("pneumaticcraft:compressed_iron_boots"       , "Pressure Treated Steel Boots")

    rename("pneumaticcraft:drill_bit_compressed_iron"   , "Pressure Treated Steel Drill Bit")
    rename("pneumaticcraft:compressed_iron_gear"        , "Pressure Treated Steel Gear")
    rename("compressedcreativity:compressed_iron_casing", "Pressure Treated Steel Casing")

    rename("car:white_suv_body"         , "White Offroader Body")
    rename("car:light_gray_suv_body"    , "Light Gray Offroader Body")
    rename("car:gray_suv_body"          , "Gray Offroader Body")
    rename("car:black_suv_body"         , "Black Offroader Body")
    rename("car:brown_suv_body"         , "Brown Offroader Body")
    rename("car:red_suv_body"           , "Red Offroader Body")
    rename("car:orange_suv_body"        , "Orange Offroader Body")
    rename("car:yellow_suv_body"        , "Yellow Offroader Body")
    rename("car:lime_suv_body"          , "Lime Offroader Body")
    rename("car:green_suv_body"         , "Green Offroader Body")
    rename("car:cyan_suv_body"          , "Cyan Offroader Body")
    rename("car:light_blue_suv_body"    , "Light Blue Offroader Body")
    rename("car:blue_suv_body"          , "Blue Offroader Body")
    rename("car:purple_suv_body"        , "Purple Offroader Body")
    rename("car:magenta_suv_body"       , "Magenta Offroader Body")
    rename("car:pink_suv_body"          , "Pink Offroader Body")

    rename("car:white_sport_body"         , "White Twang Body")
    rename("car:light_gray_sport_body"    , "Light Gray Twang Body")
    rename("car:gray_sport_body"          , "Gray Twang Body")
    rename("car:black_sport_body"         , "Black Twang Body")
    rename("car:brown_sport_body"         , "Brown Twang Body")
    rename("car:red_sport_body"           , "Red Twang Body")
    rename("car:orange_sport_body"        , "Orange Twang Body")
    rename("car:yellow_sport_body"        , "Yellow Twang Body")
    rename("car:lime_sport_body"          , "Lime Twang Body")
    rename("car:green_sport_body"         , "Green Twang Body")
    rename("car:cyan_sport_body"          , "Cyan Twang Body")
    rename("car:light_blue_sport_body"    , "Light Blue Twang Body")
    rename("car:blue_sport_body"          , "Blue Twang Body")
    rename("car:purple_sport_body"        , "Purple Twang Body")
    rename("car:magenta_sport_body"       , "Magenta Twang Body")
    rename("car:pink_sport_body"          , "Pink Twang Body")
    
    rename("car:oak_body"             , "Light Gray Maluch Body")
    rename("car:spruce_body"          , "Green Maluch Body")
    rename("car:birch_body"           , "White Maluch Body")
    rename("car:jungle_body"          , "Yellow Maluch Body")
    rename("car:acacia_body"          , "Orange Maluch Body")
    rename("car:dark_oak_body"        , "Black Maluch Body")
    rename("car:crimson_body"         , "Red Maluch Body")
    rename("car:warped_body"          , "Light Blue Maluch Body")
    
    rename("car:big_oak_body"             , "Light Gray Buchanka Body")
    rename("car:big_spruce_body"          , "Green Buchanka Body")
    rename("car:big_birch_body"           , "White Buchanka Body")
    rename("car:big_jungle_body"          , "Yellow Buchanka Body")
    rename("car:big_acacia_body"          , "Orange Buchanka Body")
    rename("car:big_dark_oak_body"        , "Black Buchanka Body")
    rename("car:big_crimson_body"         , "Red Buchanka Body")
    rename("car:big_warped_body"          , "Light Blue Buchanka Body")

    rename("car:white_transporter_body"         , "White Truck Body")
    rename("car:light_gray_transporter_body"    , "Light_gray Truck Body")
    rename("car:gray_transporter_body"          , "Gray Truck Body")
    rename("car:black_transporter_body"         , "Black Truck Body")
    rename("car:brown_transporter_body"         , "Brown Truck Body")
    rename("car:red_transporter_body"           , "Red Truck Body")
    rename("car:orange_transporter_body"        , "Orange Truck Body")
    rename("car:yellow_transporter_body"        , "Yellow Truck Body")
    rename("car:lime_transporter_body"          , "Lime Truck Body")
    rename("car:green_transporter_body"         , "Green Truck Body")
    rename("car:cyan_transporter_body"          , "Cyan Truck Body")
    rename("car:light_blue_transporter_body"    , "Light_blue Truck Body")
    rename("car:blue_transporter_body"          , "Blue Truck Body")
    rename("car:purple_transporter_body"        , "Purple Truck Body")
    rename("car:magenta_transporter_body"       , "Magenta Truck Body")
    rename("car:pink_transporter_body"          , "Pink Truck Body")

})

