
#General settings
[profiles]
	#Block to put underneath a bed so that it qualifies as a teleporter bed
	specialBedBlock = "minecraft:minecraft:structure_block"
	selectedProfile = ""
	selectedCustomJson = ""
	#The size of the todo queues for the lost city generator
	#Range: 1 ~ 100000
	todoQueueSize = 20
	#If this is true then saplings will grow into trees during generation. This is more expensive
	forceSaplingGrowth = true
	#List of structures to avoid when generating cities (for example to avoid generating a city in a woodland mansion)
	avoidStructures = [
		"creatingspace:abandoned_moon_outpost",
		"incendium:abandoned_tower",
		"idas:abandonedhouse",
		"irons_spellbooks:ancient_battleground",
		"idas:ancient_statue/ancient_statue_desert",
		"idas:ancient_statue/ancient_statue_jungle",
		"idas:ancient_statue/ancient_statue_plains",
		"idas:animal_den/forest_den",
		"idas:animal_den/foxhound_den",
		"idas:animal_den/polar_bear_den",
		"idas:apothecary_abode",
		"scguns:asgharian_citadel",
		"scguns:asgharian_tower",
		"explorify:badlands_pyramid",
		"scorched:badlands_pyramid",
		"scorched:badlands_well",
		"minecraft:bastion_remnant",
		"idas:bazaar",
		"idas:bearclaw_inn",
		"idas:beekeepers_house",
		"create_easy_structures:big_1",
		"create_easy_structures:big_2",
		"valhelsia_structures:big_tree",
		"explorify:black_spiral",
		"twigs:bloodstone_obelisk",
		"idas:brickhouse",
		"cataclysm:burning_arena",
		"create_easy_structures:camp_1",
		"create_easy_structures:camp_2",
		"create_easy_structures:camp_3",
		"create_easy_structures:camp_4",
		"create_easy_structures:camp_5",
		"sgjourney:cartouche/abydos_cartouche",
		"sgjourney:cartouche/chulak_cartouche_monument",
		"sgjourney:cartouche/sandstone_cartouche_monument",
		"sgjourney:cartouche/stone_cartouche_monument",
		"dungeons_enhanced:castle",
		"idas:castle",
		"valhelsia_structures:castle",
		"valhelsia_structures:castle_ruin",
		"bygonenether:catacomb",
		"bygonenether:citadel",
		"friendsandfoes:citadel",
		"sgjourney:city/abydos_city",
		"idas:cottage",
		"creatingspace:crashed_rocket",
		"hearths:crimson_tower",
		"cataclysm:cursed_pyramid",
		"idas:desert_camp/desert_camp",
		"idas:desert_camp/desert_camp_bygwindswept",
		"idas:desert_camp/desert_camp_orange",
		"idas:desert_camp/desert_camp_red",
		"valhelsia_structures:desert_house",
		"idas:desert_market/desert_market",
		"idas:desert_market/desert_market_orange",
		"idas:desert_market/desert_market_red",
		"minecraft:desert_pyramid",
		"scorched:desert_pyramid",
		"explorify:desert_shrine",
		"betterdeserttemples:desert_temple",
		"dungeons_enhanced:desert_temple",
		"dungeons_enhanced:desert_tomb",
		"scorched:desert_well",
		"create_easy_structures:dirt_structure",
		"dungeons_enhanced:druid_circle",
		"dungeons_enhanced:elders_temple",
		"idas:enchantingtower",
		"minecraft:end_city",
		"explorify:end_shipwreck",
		"irons_spellbooks:evoker_fort",
		"towns_and_towers:exclusives/pillager_outpost_classic",
		"towns_and_towers:exclusives/pillager_outpost_iberian",
		"towns_and_towers:exclusives/pillager_outpost_mediterranean",
		"towns_and_towers:exclusives/pillager_outpost_oriental",
		"towns_and_towers:exclusives/pillager_outpost_rustic",
		"towns_and_towers:exclusives/pillager_outpost_swedish",
		"towns_and_towers:exclusives/pillager_outpost_tudor",
		"towns_and_towers:exclusives/village_classic",
		"towns_and_towers:exclusives/village_iberian",
		"towns_and_towers:exclusives/village_mediterranean",
		"towns_and_towers:exclusives/village_nilotic",
		"towns_and_towers:exclusives/village_piglin",
		"towns_and_towers:exclusives/village_rustic",
		"towns_and_towers:exclusives/village_swedish",
		"towns_and_towers:exclusives/village_tudor",
		"towns_and_towers:exclusives/village_wandering_trader_camp",
		"create_easy_structures:factory_1",
		"create_easy_structures:factory_2",
		"idas:farmhouse",
		"idas:fishermans_lodge",
		"dungeons_enhanced:fishing_ship",
		"incendium:forbidden_castle",
		"create_easy_structures:foresttracks",
		"valhelsia_structures:forge",
		"betterfortresses:fortress",
		"minecraft:fortress",
		"sgjourney:goauld_temple/badlands_ziggurat/badlands_ziggurat",
		"sgjourney:goauld_temple/desert_pyramid/abandoned/desert_pyramid_abandoned",
		"sgjourney:goauld_temple/desert_pyramid/desert_pyramid",
		"sgjourney:goauld_temple/jungle_pyramid/jungle_pyramid",
		"luminous_depths:golden_house",
		"explorify:guide_post_cold",
		"explorify:guide_post_warm",
		"idas:haunted_manor",
		"dungeons_enhanced:hay_storage",
		"idas:hermits_hollow",
		"create_easy_structures:house_1",
		"create_easy_structures:house_2",
		"create_easy_structures:house_3",
		"create_easy_structures:house_4",
		"idas:hunters_cabin",
		"aquamirae:ice_maze/arch",
		"aquamirae:ice_maze/common",
		"aquamirae:ice_maze/spiral",
		"dungeons_enhanced:ice_pit",
		"idas:iceandfire/dread_citadel",
		"friendsandfoes:iceologer_cabin",
		"minecraft:igloo",
		"friendsandfoes:illusioner_shack",
		"friendsandfoes:illusioner_training_grounds",
		"irons_spellbooks:impaled_icebreaker",
		"incendium:infernal_altar",
		"sgjourney:jaffa_house",
		"dungeons_enhanced:jungle_monument",
		"minecraft:jungle_pyramid",
		"betterjungletemples:jungle_temple",
		"idas:labyrinth",
		"idas:lumber_camp/lumber_camp_acacia",
		"idas:lumber_camp/lumber_camp_birch",
		"idas:lumber_camp/lumber_camp_bopmahogany",
		"idas:lumber_camp/lumber_camp_bopredwood",
		"idas:lumber_camp/lumber_camp_bygmahogany",
		"idas:lumber_camp/lumber_camp_bygredwood",
		"idas:lumber_camp/lumber_camp_dark_oak",
		"idas:lumber_camp/lumber_camp_jungle",
		"idas:lumber_camp/lumber_camp_oak",
		"idas:lumber_camp/lumber_camp_spruce",
		"irons_spellbooks:mangrove_hut",
		"minecraft:mansion",
		"explorify:mausoleum",
		"towns_and_towers:mimic_desert",
		"dungeons_enhanced:miners_house",
		"minecraft:monument",
		"irons_spellbooks:mountain_tower",
		"dungeons_enhanced:mushroom_house",
		"idas:necromancers_spire",
		"minecraft:nether_fossil",
		"incendium:nether_reactor",
		"hearths:netherrack_spiral",
		"betteroceanmonuments:ocean_monument",
		"minecraft:ocean_ruin_cold",
		"minecraft:ocean_ruin_warm",
		"scguns:osgood_lab",
		"scguns:osgood_lab_outpost",
		"aquamirae:outpost",
		"bygonenether:piglin_manor",
		"incendium:piglin_village",
		"dungeons_enhanced:pillager_camp",
		"idas:pillager_camp",
		"idas:pillager_fortress",
		"minecraft:pillager_outpost",
		"towns_and_towers:pillager_outpost_badlands",
		"towns_and_towers:pillager_outpost_beach",
		"towns_and_towers:pillager_outpost_birch_forest",
		"towns_and_towers:pillager_outpost_desert",
		"towns_and_towers:pillager_outpost_flower_forest",
		"towns_and_towers:pillager_outpost_forest",
		"towns_and_towers:pillager_outpost_grove",
		"towns_and_towers:pillager_outpost_jungle",
		"towns_and_towers:pillager_outpost_meadow",
		"towns_and_towers:pillager_outpost_mushroom_fields",
		"towns_and_towers:pillager_outpost_ocean",
		"towns_and_towers:pillager_outpost_old_growth_taiga",
		"towns_and_towers:pillager_outpost_savanna",
		"towns_and_towers:pillager_outpost_savanna_plateau",
		"towns_and_towers:pillager_outpost_snowy_beach",
		"towns_and_towers:pillager_outpost_snowy_plains",
		"towns_and_towers:pillager_outpost_snowy_slopes",
		"towns_and_towers:pillager_outpost_snowy_taiga",
		"towns_and_towers:pillager_outpost_sparse_jungle",
		"towns_and_towers:pillager_outpost_sunflower_plains",
		"towns_and_towers:pillager_outpost_swamp",
		"towns_and_towers:pillager_outpost_taiga",
		"towns_and_towers:pillager_outpost_wooded_badlands",
		"incendium:pipeline",
		"dungeons_enhanced:pirate_ship",
		"valhelsia_structures:player_house",
		"irons_spellbooks:pyromancer_tower",
		"incendium:quartz_kitchen",
		"idas:redhorn_guild",
		"dungeons_enhanced:ruined_building",
		"cataclysm:ruined_citadel",
		"incendium:ruined_lab",
		"minecraft:ruined_portal",
		"minecraft:ruined_portal_desert",
		"minecraft:ruined_portal_jungle",
		"minecraft:ruined_portal_mountain",
		"minecraft:ruined_portal_nether",
		"minecraft:ruined_portal_ocean",
		"minecraft:ruined_portal_swamp",
		"idas:ruins_of_the_deep",
		"incendium:sanctum",
		"scorched:sandcrab",
		"luminous_depths:sculky_ruins",
		"luminous_depths:secret_lab",
		"aquamirae:shelter",
		"aquamirae:ship",
		"minecraft:shipwreck",
		"minecraft:shipwreck_beached",
		"betterdungeons:small_nether_dungeon",
		"idas:snifferhenge",
		"cataclysm:soul_black_smith",
		"dungeons_enhanced:stables",
		"sgjourney:stargate/classic/pedestal/stargate_pedestal",
		"sgjourney:stargate/milky_way/buried/buried_stargate",
		"sgjourney:stargate/milky_way/buried/buried_stargate_desert",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_badlands",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_cavum_tenebrae",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_chulak",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_deep_dark",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_desert",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_glacio",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_jungle",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_mushroom",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_nether",
		"sgjourney:stargate/milky_way/pedestal/stargate_pedestal_snow",
		"sgjourney:stargate/milky_way/temple/abydos_pyramid",
		"sgjourney:stargate/milky_way/temple/great_pyramid",
		"sgjourney:stargate/milky_way/terra_stargate",
		"sgjourney:stargate/pegasus/outpost/lantean_outpost_ocean",
		"sgjourney:stargate/pegasus/pegasus_stargate",
		"sgjourney:stargate/universe/destiny",
		"sgjourney:stargate/universe/pedestal/universe_stargate_pedestal_end",
		"create_easy_structures:station",
		"cataclysm:sunken_city",
		"idas:sunken_ship/sunken_ship",
		"idas:sunken_ship/sunken_ship_coral",
		"idas:sunken_ship/sunken_ship_ruins",
		"dungeons_enhanced:sunken_shrine",
		"minecraft:swamp_hut",
		"dungeons_enhanced:tall_witch_hut",
		"idas:tinkers_workshop",
		"dungeons_enhanced:tower_of_the_undead",
		"valhelsia_structures:tower_ruin",
		"minecraft:trail_ruins",
		"idas:train_ruins",
		"dungeons_enhanced:tree_house",
		"idas:tree_of_wisdom",
		"idas:treetop_tavern",
		"scguns:trench",
		"towns_and_towers:village_badlands",
		"towns_and_towers:village_beach",
		"towns_and_towers:village_birch_forest",
		"minecraft:village_desert",
		"towns_and_towers:village_flower_forest",
		"towns_and_towers:village_forest",
		"towns_and_towers:village_grove",
		"towns_and_towers:village_jungle",
		"towns_and_towers:village_meadow",
		"towns_and_towers:village_mushroom_fields",
		"towns_and_towers:village_ocean",
		"towns_and_towers:village_old_growth_taiga",
		"minecraft:village_plains",
		"minecraft:village_savanna",
		"towns_and_towers:village_savanna_plateau",
		"minecraft:village_snowy",
		"towns_and_towers:village_snowy_slopes",
		"towns_and_towers:village_snowy_taiga",
		"towns_and_towers:village_sparse_jungle",
		"towns_and_towers:village_sunflower_plains",
		"towns_and_towers:village_swamp",
		"minecraft:village_taiga",
		"towns_and_towers:village_wooded_badlands",
		"hearths:warped_tower",
		"idas:washing_camp",
		"dungeons_enhanced:watch_tower",
		"explorify:watchtower_plains",
		"explorify:watchtower_savanna",
		"explorify:watchtower_taiga",
		"supplementaries:way_sign",
		"create_easy_structures:windmill",
		"idas:winter_wagon",
		"valhelsia_structures:witch_hut",
		"dungeons_enhanced:witch_tower",
		"idas:witches_treestump",
		"idas:wizard_tower",
		"towns_and_towers:wreckage_ocean"]
	#If true then also avoid generating the structures mentioned in 'avoidStructures' in chunks adjacent to the chunk with the structure
	avoidStructuresAdjacent = true
	#If true then also avoid generating cities in chunks adjacent to the chunks with villages
	avoidVillagesAdjacent = false
	#If true then avoid generating cities in chunks with villages
	avoidVillages = true
	#If true then avoid flattening the terrain around the city in case there was a structure that was avoided
	avoidFlattening = false

