[minecraft:overworld]
biomesoplenty:cold_desert > minecraft:snowy_taiga
biomesoplenty:muskeg > minecraft:snowy_taiga
biomesoplenty:tundra > minecraft:snowy_taiga
biomesoplenty:snowy_fir_clearing > minecraft:snowy_taiga
biomesoplenty:fir_clearing > minecraft:taiga
biomesoplenty:mystic_grove > minecraft:snowy_taiga
minecraft:grove > minecraft:snowy_taiga
minecraft:frozen_ocean > minecraft:cold_ocean

[lostcities:lostcity]
biomesoplenty:aspen_glade > biomesoplenty:wasteland
biomesoplenty:auroral_garden > biomesoplenty:wasteland
biomesoplenty:bayou > biomesoplenty:wasteland
biomesoplenty:bog > biomesoplenty:wasteland
biomesoplenty:clover_patch > biomesoplenty:wasteland_steppe
biomesoplenty:coniferous_forest > biomesoplenty:wasteland
biomesoplenty:erupting_inferno > biomesoplenty:wasteland
biomesoplenty:field > biomesoplenty:wasteland
biomesoplenty:fir_clearing > biomesoplenty:wasteland
biomesoplenty:forested_field > biomesoplenty:wasteland
biomesoplenty:grassland > biomesoplenty:wasteland_steppe
biomesoplenty:highland > biomesoplenty:wasteland
biomesoplenty:jacaranda_glade > biomesoplenty:wasteland
biomesoplenty:jade_cliffs > biomesoplenty:wasteland
biomesoplenty:lavender_field > biomesoplenty:wasteland_steppe
biomesoplenty:lavender_forest > biomesoplenty:wasteland
biomesoplenty:lush_desert > biomesoplenty:wasteland
biomesoplenty:lush_savanna > biomesoplenty:wasteland
biomesoplenty:maple_woods > biomesoplenty:wasteland
biomesoplenty:marsh > biomesoplenty:wasteland
biomesoplenty:mediterranean_forest > biomesoplenty:wasteland_steppe
biomesoplenty:moor > biomesoplenty:wasteland
biomesoplenty:mystic_grove > biomesoplenty:wasteland
biomesoplenty:old_growth_woodland > biomesoplenty:old_growth_dead_forest
biomesoplenty:orchard > biomesoplenty:wasteland
biomesoplenty:origin_valley > biomesoplenty:wasteland
biomesoplenty:overgrown_greens > biomesoplenty:wasteland_steppe
biomesoplenty:pasture > biomesoplenty:wasteland_steppe
biomesoplenty:prairie > biomesoplenty:wasteland_steppe
biomesoplenty:pumpkin_patch > biomesoplenty:wasteland
biomesoplenty:rainforest > biomesoplenty:wasteland
biomesoplenty:redwood_forest > biomesoplenty:wasteland
biomesoplenty:rocky_rainforest > biomesoplenty:wasteland
biomesoplenty:rocky_shrubland > biomesoplenty:wasteland_steppe
biomesoplenty:scrubland > biomesoplenty:wasteland_steppe
biomesoplenty:seasonal_forest > biomesoplenty:wasteland
biomesoplenty:seasonal_orchard > biomesoplenty:wasteland
biomesoplenty:shrubland > biomesoplenty:wasteland_steppe
biomesoplenty:snowblossom_grove > biomesoplenty:wasteland
biomesoplenty:snowy_coniferous_forest > biomesoplenty:wasteland
biomesoplenty:snowy_fir_clearing > biomesoplenty:wasteland_steppe
biomesoplenty:snowy_maple_woods > biomesoplenty:wasteland
biomesoplenty:tropics > biomesoplenty:wasteland
biomesoplenty:tundra > biomesoplenty:wasteland_steppe
biomesoplenty:undergrowth > biomesoplenty:wasteland
biomesoplenty:visceral_heap > biomesoplenty:wasteland
biomesoplenty:wetland > biomesoplenty:wasteland
biomesoplenty:wintry_origin_valley > biomesoplenty:wasteland
biomesoplenty:withered_abyss > biomesoplenty:wasteland
biomesoplenty:woodland > biomesoplenty:wasteland
minecraft:badlands > biomesoplenty:wasteland
minecraft:bamboo_jungle > biomesoplenty:wasteland
minecraft:beach > biomesoplenty:wasteland
minecraft:birch_forest > biomesoplenty:dead_forest
minecraft:cherry_grove > biomesoplenty:dead_forest
minecraft:cold_ocean > biomesoplenty:wasteland
minecraft:coniferous_forest > biomesoplenty:dead_forest
minecraft:dark_forest > biomesoplenty:dead_forest
minecraft:desert > biomesoplenty:wasteland
minecraft:eroded_badlands > biomesoplenty:wasteland
minecraft:flower_forest > biomesoplenty:dead_forest
minecraft:forest > biomesoplenty:dead_forest
minecraft:jungle > biomesoplenty:old_growth_dead_forest
minecraft:mangrove_swamp > biomesoplenty:old_growth_dead_forest
minecraft:meadow > biomesoplenty:wasteland_steppe
minecraft:old_growth_birch_forest > biomesoplenty:old_growth_dead_forest
minecraft:old_growth_pine_taiga > biomesoplenty:old_growth_dead_forest
minecraft:old_growth_spruce_taiga > biomesoplenty:old_growth_dead_forest
minecraft:plains > biomesoplenty:wasteland
minecraft:river > biomesoplenty:wasteland
minecraft:savanna > biomesoplenty:wasteland
minecraft:savanna_plateau > biomesoplenty:wasteland
minecraft:seasonal_forest > biomesoplenty:dead_forest
minecraft:snowy_beach > biomesoplenty:wasteland
minecraft:snowy_plains > biomesoplenty:wasteland
minecraft:snowy_taiga > biomesoplenty:dead_forest
minecraft:sparse_jungle > biomesoplenty:wasteland_steppe
minecraft:sunflower_plains > biomesoplenty:wasteland
minecraft:swamp > biomesoplenty:wasteland
minecraft:taiga > biomesoplenty:dead_forest
minecraft:windswept_forest > biomesoplenty:dead_forest
minecraft:windswept_savanna > biomesoplenty:wasteland_steppe
minecraft:wooded_badlands > biomesoplenty:dead_forest
quark:glimmering_weald > biomesoplenty:dead_forest