[minecraft:overworld]
biomesoplenty:cold_desert > null
biomesoplenty:muskeg > null
biomesoplenty:tundra > null

[lostcities:lostcity]
biomesoplenty:aspen_glade > null
biomesoplenty:auroral_garden > null
biomesoplenty:bayou > null
biomesoplenty:bog > null
biomesoplenty:clover_patch > null
biomesoplenty:cold_desert > null
biomesoplenty:coniferous_forest > null
biomesoplenty:erupting_inferno > null
biomesoplenty:field > null
biomesoplenty:fir_clearing > null
biomesoplenty:forested_field > null
biomesoplenty:fungal_jungle > null
biomesoplenty:glowing_grotto > null
biomesoplenty:grassland > null
biomesoplenty:highland > null
biomesoplenty:hot_springs > null
biomesoplenty:jacaranda_glade > null
biomesoplenty:jade_cliffs > null
biomesoplenty:lavender_field > null
biomesoplenty:lavender_forest > null
biomesoplenty:lush_desert > null
biomesoplenty:lush_savanna > null
biomesoplenty:maple_woods > null
biomesoplenty:marsh > null
biomesoplenty:mediterranean_forest > null
biomesoplenty:moor > null
biomesoplenty:muskeg > null
biomesoplenty:mystic_grove > null
biomesoplenty:old_growth_dead_forest > null
biomesoplenty:old_growth_woodland > null
biomesoplenty:ominous_woods > null
biomesoplenty:orchard > null
biomesoplenty:origin_valley > null
biomesoplenty:overgrown_greens > null
biomesoplenty:pasture > null
biomesoplenty:prairie > null
biomesoplenty:pumpkin_patch > null
biomesoplenty:rainforest > null
biomesoplenty:redwood_forest > null
biomesoplenty:rocky_rainforest > null
biomesoplenty:rocky_shrubland > null
biomesoplenty:scrubland > null
biomesoplenty:seasonal_forest > null
biomesoplenty:seasonal_orchard > null
biomesoplenty:shrubland > null
biomesoplenty:snowblossom_grove > null
biomesoplenty:snowy_coniferous_forest > null
biomesoplenty:snowy_fir_clearing > null
biomesoplenty:snowy_maple_woods > null
biomesoplenty:tropics > null
biomesoplenty:tundra > null
biomesoplenty:undergrowth > null
biomesoplenty:visceral_heap > null
biomesoplenty:wetland > null
biomesoplenty:wintry_origin_valley > null
biomesoplenty:withered_abyss > null
biomesoplenty:woodland > null