#This should under no circumstances be set to true in modpacks
#If set to true, the mod creates a new global folder, that is global for your user on your computer.
#The created folders will be:
# <user_home>/.minecraft_global_packs/required_datapacks
# <user_home>/.minecraft_global_packs/optional_datapacks
# <user_home>/.minecraft_global_packs/required_resourcepacks
# <user_home>/.minecraft_global_packs/optional_resourcepacks
enable_system_global_packs = false

#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft or instance folder
#With the current config you can place a Datapack into '.minecraft/global_packs/required_data' to force enable a datapack.
[resourcepacks]
required = [
    #"other_folder/random_pack.zip" # You can also point at specific files!
    "resourcepacks/07_Better tom's create storage 1.1.zip",
    "resourcepacks/06_Create Computers 1.2.1 - 1.20.1 Resource Pack Only.zip",
    "resourcepacks/05_Create_Guns_Scorched_1.19.2-1.19.3.zip",
    "resourcepacks/04_Create Guns 1.2.1 - 1.20.1.zip",
    "resourcepacks/03_Create+Simple+Storage+2.1.zip",
    "resourcepacks/02_Eureka+Create+1.0.zip",
    "resourcepacks/01_UltimateCarsReskin.zip"
]

[datapacks]
required = [
    "resourcepacks/",
    "global_packs/required_data/"
]

optional = [
    "global_packs/optional_data/"
]