
[logbegone]
	phrases = ["Error rendering overlay","Detected setBlock in a far chunk","Client does not have access to this information","shipObjectWorld is null","Missing textures in model"]
	regex = ["Error rendering overlay","Detected setBlock in a far chunk","Client does not have access to this information","shipObjectWorld is null","Missing textures in model"]

